### PR TITLE
FIX: Support absolute path for Media Folder (#119)

### LINKED ISSUE #119: Support absolute path for Media Folder
It would be great to have the option to chose one folder for the project where all images can be stored. 
I currently don't see a way to do this with relative image paths, because working with "../" breaks when you work with different levels of subfolders.

### PR DESCRIPTION
**Pull request by kiyoka**
Support absolute path for Media Folder.
To give VSCode permission for absolute paths, we set the localResourceRoots to that absolute folder path.
image

**Unotes version:**
1.4.1

## Description
- Fixes #119 

## Tested
- Set "../images" to Media Folder, pasted an image from the clipboard, and the image was saved in "../images".
- Set "/images" to Media Folder, pasted an image from the clipboard, and the image was saved in "/images".

## Question
I know development is going on in the editor branch, should I rework the pull request for the editor branch?

### CODE REVIEW

**Review by ryan-mcalister — APPROVED** [review]
Thanks for the PR! Looks great. I'll take care of merging it into the editor branch, thanks!

File: editor/src/TuiEditor.js [hunk 1]
```diff
@@ -157,7 +161,11 @@ class TuiEditor extends Component {
     }
 
     onHtmlBefore(e) {
-        return replaceAll(e, img_root, '');
+        let str = replaceAll(e, img_root, '');
+        if (str) {
+         str = replaceAll(str, 'file://', '');
```
Comment (ryanmcalister) [inline editor/src/TuiEditor.js:166]: What was the motivation for this change?
